### PR TITLE
Re-enable and break up script that handles unregister_netdevice

### PR DESCRIPTION
**Pull request by meatballhat**

### CODE REVIEW

**Comment by meatballhat** [comment]
This is working correctly in staging :+1:

**Comment by meatballhat** [comment]
Confirmed working correctly on an elder production worker instance :+1:

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
@meatballhat any reason why we cannot get rid of this completely once we've upgraded to mainline?

**Comment by meatballhat** [comment]
@igorwwwwwwwwwwwwwwwwwwww I consider this a reasonable safeguard regardless of the kernel version we're on.  If the error ever re-surfaces, for whatever reason, we'll be prepared.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Okay, I'm fine with keeping it around. :)

**Pull request merged**
