### PR TITLE
[gce-staging-1] Increase size of subnets to match what we are going for in production

### PR DESCRIPTION
**Pull request by igorwwwwwwwwwwwwwwwwwwww**

### CODE REVIEW

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
This has been applied to staging.

**Comment by henrikhodne** [comment]
Would it be good to use the same ranges as in production? `10.10.8.0/22` for .org and `10.10.12.0/22` for .com?

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
can do, what should we do with the `public` and `workers` subnets?

**Comment by henrikhodne** [comment]
`10.10.0.0/22` and `10.10.4.0/22`?

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
done!

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
also applied now.

**Pull request merged**
